language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - cd tests; python -m unittest
  - [[ ! -z "$TRAVIS_PULL_REQUEST" ]] && cd use_cases; python -m unittest